### ISSUE TITLE
The sync of the single file to a specific path with a different name maintains source name

### ISSUE THREAD

**Issue by geaaru** [MottainaiCI/lxd-compose#1]
```yaml
            sync_resources:
              # source: File or directory to push
              # dst: File or directory target. For directory is needed "/" at the end
              - source: files/myconf.conf.yaml
                dst: /etc/myapp/myconf.conf.yml
```

Instead of creating myconf.conf.yml on container is maintained the origin myconf.conf.yaml file.
