### ISSUE TITLE
Integrate the option `user` to the hook to run commands with a specified user

### ISSUE THREAD

**Issue by geaaru** [MottainaiCI/lxd-compose#4]
The idea is to have a way to run commands with a specified user instead of root.

ASIS:
```yaml
            hooks:
              - event: post-node-sync
                flags:
                  - start_steam
                commands:
                  - su ubuntu -c steam
```
TOBE:
```yaml
            hooks:
              - event: post-node-sync
                user: ubuntu
                flags:
                  - start_steam
                commands:
                  - steam
```

**Comment by geaaru** [comment]
The LXD API doesn't permit to use directly the user name but the uid. For now I'm using directly the API available but could be parsed the /etc/shadow and /etc/group files in the future to improve this feature.

**Comment by geaaru** [comment]
Hereinafter, the example of the implemented logic
```
            hooks:
              - event: post-node-sync
                uid: 1000
                gid: 1000
                cwd: /home/ubuntu/steam
                flags:
                  - start_steam
                commands:
                  - steam
```
The `cwd` option permits to define the path where execute the hook.
